### PR TITLE
Solves issue #360

### PR DESCRIPTION
**Pull request by eschiendorfer**
Not sure if it's the correct/nice way to do it. With this chang, it only joins, if there is an attribute.

### CODE REVIEW

**Comment by eschiendorfer** [comment]
Is the way of my pull requets correct? Somehow it seems to group them always. Is it not possible to change a pull request? I made a typo in the description...

**Comment by Traumflug** [comment]
Yes, pull requests happen per branch in your repo. Which means, for having an independent request one has to create another branch and request that. It also means that changing a branch changes/updates the related pull request.

For changing a commit description (or code) there's `git commit --amend` if it happens to be the latest commit in a branch. For changing earlier commits, there's `git rebase -i <some earlier commit>`.  `push -f`-ing the changed branch to Github then also changes the pull request. Reading up on "Git topic branches" should give additional help, e.g. here: https://blog.mozilla.org/webdev/2011/11/21/git-using-topic-branches-and-interactive-rebasing-effectively/

Hint: I use Git since v1.0 (some 10 years now) and so far *never* used `git merge`. What Mozilla developers describe as "Ninja strategies" works so much better.

**Comment by eschiendorfer** [comment]
Oh thanks for your comment! I don't use command line. I am just starting with github :D But I understand now how to do it.

My pull request is now green again. Does this mean you will merge it in next version? Did you check my changes or do you just believe me? ^^

**Comment by Traumflug** [comment]
> I don't use command line.

Forget it, then. Advanced Git usage can't be done in a GUI, just like one can't write PHP or JS code using a GUI.

**Comment by firstred** [comment]
Just tested it. Looks good to me, let's just merge it for now. Thanks!

**Pull request merged**
