### PR TITLE
Remove ISO from default language URL when multilang.

### PR DESCRIPTION
**Pull request by therampagerado**
Related to: https://github.com/thirtybees/thirtybees/issues/1920

Known bug:
- when switching from default to non-default language - it is working
- when switching back - the shop is stuck on the non-default language.

### CODE REVIEW

**Comment by getdatakick** [comment]
Hi,

thank you for the PR. I've used it as a base code, and extended it a little bit to include additional options.
I've pushed in in branch issue-1920. Please help me test the solution -- it is possible to update to that branch using core updater.

I've also added an option to change language friendly url -- it no longer needs to be language iso code. Probably nobody will use it, but I think it's a nice touch.

**Comment by therampagerado** [comment]
Thank you,

Will test it today.

**Comment by therampagerado** [comment]
@getdatakick 

I did a short test and found 2 bugs that are probably related - you fixed the same behavior for my module doing the same last month.

1. When on Authentication page and non-default language the form is loaded in the default lang. When you get out of this page the site language is switched to default.
2. On a category page when you select Layered Nav filter it loads the default translation, URLs, everything. When you get out of this page the site language is switched to default.

You did some cookies magic to fix those issues.

A demo: 

1. https://test2.rampagesport.eu/login?back=my-account - switch to BG - you see 'Създай акаунт' (Create an account), when you click on the button it loads the default lang version (EN in this case).
2. https://test2.rampagesport.eu/gifts - click on "Производител" (Manufacturer) filter and look it loads the filter in EN, not in BG. (for the layered nav only this is translated so the rest of the titles will be in EN always).


I'll continue with more manual tests that I can think of, but overall I think it works perfectly.

**Comment by therampagerado** [comment]
3. Breadcrumbs home link is always default language in non-default language.


This bug is present on my production too, I have not noticed it until now.

**Comment by getdatakick** [comment]
Thanks for testing.

Problems 1 and 2 were fixed in core. See description in commit ada42cf5e6aab6d3f1fbcff56ce6c38b7ec356b4

Problem 3 -- this is a theme issue. Theme simply redirects user to `/` and, and expect thirty bees to pick up current language from cookie and redirect to language variant. This no longer works, because this url `/` is now valid even in multistore env. There is no fix for core -- the theme needs to be fixed.

See commit in niara: https://github.com/thirtybees/niara/commit/ceecca83a97b2b5f12340bc8c6b33ed7e0211eca

**Comment by getdatakick** [comment]
Now this is part of bleeding edge. Thanks again for original code, and for testing

**Pull request closed without merging**
