### PR TITLE
FO : New currency format

### PR DESCRIPTION
**Pull request by idnovate**

### CODE REVIEW

**Comment by Traumflug** [comment]
Thanks for the contribution.

- Joined 3 commits (one for each file) into one.
- Dropped two merges bringing no changes.
- Fixed misnamed variables.
- Fixed an introduced syntax error in CurrenciesController.
- Fixed whitespace.

Does this work for you? https://github.com/thirtybees/thirtybees/commit/2b969ea06594ca6f93da1dcef128ffaaac705aa3

**Comment by idnovate** [comment]
Sorry, again copied from PS repo and didn't test it at TB. Let me check it.

**Comment by idnovate** [comment]
There was an error! Fixed and checked:
http://imagizer.imageshack.com/img921/1307/vR4lNM.png
http://imagizer.imageshack.com/img922/9493/YbR3Dy.jpg

**Comment by Traumflug** [comment]
Thanks for duplicating my work :-)

I take the reviewed commit works. If not, please open another issue.

**Pull request closed without merging**
