### PR TITLE
Add customer message in order page

### PR DESCRIPTION
**Pull request by ImkerW**
I noticed we can't view customer messages in the order page, I found this function verry usefull that is why I want to suggest bringing it back for a better communication with customers.

If the quality of the code isn't good enough please improve it. I think alot of people will be happy with this.

### CODE REVIEW

**Comment by yaniv14** [comment]
You cannot commit and ask PR for override class.

**Comment by Traumflug** [comment]
It's pretty trivial to move such code into the core class, so no objection.

The more interesting question is whether this code is helpful or fixes something.

**Comment by therampagerado** [comment]
It is helpful for me - sometimes the customers require Pickup delivery at local depot and they ask for that in message at the end of the order. Then I have to click on Customer service to notice that. Needless to say - few times this didn't happen :D

Good addition imho!

Also - when customer enters only one phone number (home or mobile) they don't display sometimes (I belive it's home number). If this could be fixed by:

If(mobile)->display(mobile)
Ifno(mobile)->display(home)

This could be great too!

**Comment by getdatakick** [comment]
This pull request seems to be irelevant now.

Since commit 386503afb00febeaf39943a8d033c3225ce6d40c, method `Message::getMessagesByOrderId` is no longer used anywhere in the core (we should deprecate it).

I'm closing this pull request, as it looks like the `CustomerMessage::getMessagesByOrderId` implements the same think already. If it's not true. If not, please open new pull request, based on latest codebase.

**Pull request closed without merging**
