### PR TITLE
Design of the Friendly URL options

### PR DESCRIPTION
**Pull request by Traumflug**
Fix two of the issues brought up here: https://forum.thirtybees.com/topic/39/references-to-prestashop-and-missing-tooltips/2

### CODE REVIEW

**Comment by firstred** [comment]
Thanks, but thirty bees is spelled lowercase.

If you change that, then I can merge your PR.

**Comment by inetbiz** [comment]
Woops! Didn't see @firstred comment lol

**Comment by Traumflug** [comment]
Should be fixed now.

**Comment by Traumflug** [comment]
Rebased this to current *master*.

**Comment by firstred** [comment]
Thank you!

**Pull request merged**
