### PR TITLE
Fix variable name

### PR DESCRIPTION
**Pull request by mauroagr**
The variable name was $ecimals, but the right is $decimals

### CODE REVIEW

**Comment by Traumflug** [comment]
Nice catches!

**Comment by Traumflug** [comment]
Looking closer into this, I'm no longer convinced of fe167b5.

- Rounding to `$decimals` makes sense only for prices to display. Which means, using the configuration value rather than the constant is better.
- `Tools::convertPrice()` rounds to database precision already, no need to do this again on the returned value.

Did this second commit fix some particular situation? It's well possible that all usages of `$decimals` in this method simply can get removed. Knowing which situation it solves would allow a better opinion on the best solution.

**Comment by mauroagr** [comment]
@Traumflug The first commit update the ```$ecimals``` to ```$decimal```, i think was a wrong variable name.
The secund commit, i make thinking that database precision is the same as price precision, but reading now, i think make mistake.

**Comment by Traumflug** [comment]
Fine. First commit was applied with 849810829525998c9799dab417a605de1e73914b already, thanks again for that. The other one is no longer needed.

**Pull request closed without merging**
