### PR TITLE
CO : Fixed error with redirections

### PR DESCRIPTION
**Pull request by idnovate**
https://www.prestashop.com/forums/topic/910826-redirection-https-vers-http-vers-https-si-www/

### CODE REVIEW

**Comment by Traumflug** [comment]
Origin by @jeckyl: https://github.com/PrestaShop/PrestaShop/pull/11004/commits/b213fe7844bd621c38dcdc2ad1dbeabba373ba52

**Comment by Dh42** [comment]
I agree, that is so much faster than having it travel through php.

**Comment by Traumflug** [comment]
I'd be happier if I could reproduce something not working ideally. Without the patch everything works just fine

`http://localhost/thirtybees`
redirects 301 to
`https://localhost/thirtybees/`
redirects 302 to
`https://localhost/thirtybees/en/`

**Comment by Traumflug** [comment]
@Zengraph found a simpler solution for this, which entered *1.0.x*: f1877ee1baeabf973b825ef59e47b482b69fb6c4

Thank you very much for the heads up, anyways.

**Pull request closed without merging**
