### PR TITLE
Created edit for Specific Price

### PR DESCRIPTION
**Pull request by Yecni**
I have created a edit for specific Prices.
At first I've had this in override classes but I'd like to share this with other Thirtybees users so I've put the code in the core classes. I hope everything is by the code standards.

If something is wrong or needs to be improved please let me know!

### CODE REVIEW

**Comment by SLiCK-303** [comment]
a much needed mod!

**Comment by getdatakick** [comment]
Thank you very much for your contribution, this is indeed very needed enhancement. I'll pick your changes to the 1.1.x with some small modification.

Amazing job

**Comment by Traumflug** [comment]
Some parts look indeed good. Adding another form for editing smells like duplicate code. I'd bet one can re-use the form for adding a specific price.

**Comment by getdatakick** [comment]
Picked via commit adc8c5119144558e68e4b5903050106c27f2e811

**Pull request closed without merging**
