### PR TITLE
added isRtl variable to templates

### PR DESCRIPTION
**Pull request by yaniv14**

### CODE REVIEW

**Comment by yaniv14** [comment]
Why is this being closed?

**Comment by firstred** [comment]
Thw target branch was removed which seems to have closed this PR. Sorry for that!

Can you nake a

**Comment by firstred** [comment]
It was automatically closed because the master branch has been removed. No worries though. I'll just point your commits at 1.0.x

**Comment by yaniv14** [comment]
Great, because this variable is important for my other PR in the community theme repo

**Comment by firstred** [comment]
Closing, because I saw this in your other PR.

**Pull request closed without merging**
