### PR TITLE
Add mail alerts issue #317

### PR DESCRIPTION
**Pull request by inetbiz**
Issue #317 fixes git submodule mailalerts missing. https://github.com/thirtybees/mailalerts

### CODE REVIEW

**Comment by alwayspaws** [comment]
Thanks, Denver! @inetbiz

**Comment by inetbiz** [comment]
@alwayspaws https://github.com/thirtybees/mailalerts/pull/2 is the other code merge request that actually changes everything in the modules /mail folder.

**Comment by firstred** [comment]
That doesn't work and we do not include all modules

**Comment by alwayspaws** [comment]
Sorry. This was confusing to me, so I'll stay out of it. Sorry Michael and Denver.

**Comment by Traumflug** [comment]
Modules with their Git repository being a submodule of the main thirty bees Git repository get included into the standard distribution. The module update mechanism, however, looks at all module repositories, not only those.

**Pull request closed without merging**
